### ISSUE TITLE
Duplicate tick labels on axis update

### ISSUE THREAD

**Issue by maybelinot** [Olical/react-faux-dom#141] opened 2018-11-07 19:14 UTC
Can you help me figure out what's going wrong with the update of axis domain? 

here are two examples of the same update in pure d3 and d3 in react-faux:
https://codepen.io/anon/pen/gQMwNO
https://codepen.io/anon/pen/EOPoBG

The problem is that react-faux example creates duplicate '2000' label after update.
Thanks!

**Comment by Olical** [comment] 2018-11-14 10:56
I'm going to close this _for now_. I think it's because `scale` mutates the DOM after it's rendered which this library does not support. You'll either have to use the animation mixin (which I don't really have any experience with) or use D3 directly and opt out of React updates with lifecycle hooks, avoiding ReactFauxDOM entirely (this will work fine and you should definitely consider it! :smile:).

I'm only really maintaining parts of this project where there's very clear bugs, but as far as I can tell it's working as intended here, it just doesn't support things that mutate the DOM it's working with.

**Closed by Olical** 2018-11-14 10:56 UTC
