### ISSUE TITLE
Circle radius is NaN if adding d3 enter.

### ISSUE THREAD

**Issue by royipressburger** [Olical/react-faux-dom#135] opened 2018-07-30 09:57 UTC
Hi all

Im trying to create a bubble view with `d3-hierarchy` using `pack`.
If I'm using d3 without the `faux-dom` everything works great, also if I'm using `withFauxDOM` most of the things still working. 
The issue starts when I'm adding `enter` so I can add animation for the bubbles on first render.

this is the code:
```js
  componentDidMount() {
    this.draw();
  }

  draw() {
    const size = 1000;
    const faux = this.props.connectFauxDOM('svg', 'bubbles');
    const dataSet = { children: this.props.data };
    const bubbleSizeScale = scaleSqrt()
      .domain([
        this.props.data[sortedData.length - 1].value,
        this.props.data[0].name,
      ])
      .range([50, 100]);

    const bubbles = pack(dataSet)
      .size([size, size])
      .radius(d => bubbleSizeScale(d.value))
      .padding(5);

    const svg = d3Select(faux)
      .attr('viewBox', `0 0 ${size} ${size}`)
      .attr('width', size)
      .attr('height', size)
      .attr('class', 'bubble');

    const nodes = hierarchy(dataSet).sum(d => d.value);
    const node = svg.selectAll('.node')
      .data(bubbles(nodes).descendants())
      .enter()
      .filter(d => !d.children)
      .append('g')
      .attr('class', 'node')
      .attr('transform', d => `translate(${d.x},${d.y})`);

    node
      .append('circle')
      .enter() // --> Problem starts here..
      .attr('r', d => d.r);

    node.append('text')
      .attr('dy', '.2em')
      .style('text-anchor', 'middle')
      .text(d => d.data.name);

    node.append('text')
      .attr('dy', '2em')
      .style('text-anchor', 'middle')
      .text(d => d.data.value);

    // This is prep for animation.
    console.log(d3Select(faux).selectAll('circle'));
    d3Select(faux).selectAll('circle')
      .transition()
      .duration(1000)
      .attr('r', d => d.r);
    this.props.animateFauxDOM(1000)
  }

  render() {
    return (
      <div className="bubbles">
        {
          this.props.bubbles
        }
      </div>
    );
  }
```

If I remove the the `enter` line on circle everything render fine just without animation.
But I do want animation for the circles render.
Again if I'm using d3 only everything render with the animation.

Am I using this library correctly?
Let me know if more info is require.
Thanks

**Comment by royipressburger** [comment] 2018-07-31 08:46
Hi @Olical :)

Didn't manage to find a way to fix it, right now Im without animation, but I want it.
When I debug I see that in the part after the `.transition().duration(1000)` the value of `d.r` is fine and it is what I expected.
When trying to debug at the part where I append the `circle` the break point doesn't stop there.
I placed two breakpoints at `attr('r', ...)`: One at the part of `append('circle')`, And the other after the `transition()`.

**Comment by royipressburger** [comment] 2018-08-06 13:31
@Olical Hi again. Did you a chance to look on it?

**Comment by Olical** [comment] 2018-08-07 08:09
Not yet, really busy at the moment and away over the rest of this week, so might struggle to find time.

When I do get around to it, all I'll be doing is trying to re-produce your setup and just adding a bunch of logging / stepping through the debugger. If you spot anything that's undefined when it shouldn't be or something let me know, could help a lot :smile:

**Comment by royipressburger** [comment] 2018-08-07 11:17
@Olical Sure ill try to :)

**Comment by royipressburger** [comment] 2018-08-07 11:53
@Olical Hi again. So I mange to narrow it down a bit, now im stuck :)

I found out that inside `_element.js` row 107
`Element.prototype.setAttribute = function (name, value) ...`
When the name is `r` im getting value `NaN` I have no idea why. When I print the raduis in my code it is not NaN...
I also tried to add `if (name == "r") value = 50`, and things started to work.
I still in this case dont see any animation but my screen does render without any exception.

When you will have time let me know :)

**Comment by royipressburger** [comment] 2018-08-07 12:09
Update: 

I dont see `d3-selection` `setAttribute` or `setAttributeNS` being called with `r`

**Comment by royipressburger** [comment] 2018-08-07 12:26
@Olical Ok I mange to get it working :)
Dont know why the issue didn't exists with pure `d3` 

But here is the solution:
If you look at my first code the line where i draw the circle is like this

```js
// Here I draw the circle
 node
      .append('circle')
      .enter() // --> Problem starts here..
      .attr('r', d => d.r);

 // This is prep for animation.
 d3Select(faux).selectAll('circle')
      .transition()
      .duration(1000)
      .attr('r', d => d.r);
```

I changed it to this:
```js
// Here I draw the circle
 node
      .append('circle')
      .enter()

// Reselect the circles after enter solved it.
node.selectAll('circle')
      .attr('r', d => 1);

 // This is prep for animation.
 d3Select(faux).selectAll('circle')
      .transition()
      .duration(1000)
      .attr('r', d => d.r);
```

**Comment by Olical** [comment] 2018-08-13 08:37
Since you got it working and I can't reproduce this (see 91dff53) I'm going to close this. Feel free to re-open if things keep acting weird though!

**Closed by Olical** 2018-08-13 08:37 UTC
