### ISSUE TITLE
d3.mouse always returns [NaN, NaN]

### ISSUE THREAD

**Issue by sungwoncho** [Olical/react-faux-dom#66] opened 2016-08-25 02:05 UTC
Version: latest react-faux-dom (2.7.1) and React 15.1.0.

When I do:

```js
    const node = ReactFauxDOM.createElement('svg');

    const svg = d3.select(node)
        .attr('width', width + margin.left + margin.right)
        .attr('height', h + margin.top + margin.bottom)
      .append('g')
        .attr('transform', `translate(${margin.left}, ${margin.top})`);
    ...

    svg.append('rect')
      .attr('width', width)
      .attr('height', h)
      .style('fill', 'none')
      .style('pointer-events', 'all')
      .on('mousemove', function() {
        const pos = d3.mouse(this);
        console.log(pos);
      });
```

`pos` is always `[NaN, NaN]`.

I can confirm that `this` inside the `mousemove` callback  is a DOM element (e.g. `Element {nodeName: "rect", parentNode: Element, childNodes: Array[0], eventListeners: Object, text: ""…}`).

Any ideas why?

**Comment by Olical** [comment] 2016-08-25 08:52
Are you sure your width and height are correct? `width + margin.left + margin.right` evaluates to a number and not `NaN`?

**Comment by Olical** [comment] 2016-08-25 09:03
Also, I'd try setting a breakpoint, maybe around [here](https://github.com/Olical/react-faux-dom/blob/fe4194d37675ef5a44ea38d32c9824eeb72b6f06/lib/Element.js#L240-L246), and looking for anything suspicious. `d3.mouse` uses a function called `point` which accesses `getBoundingClientRect`, something that was added pretty recently.

**Comment by BeshoyLouka** [comment] 2016-08-30 20:13
@sungwoncho I am using the d3 event for now:
```
...
      .on('mousemove', function() {
        console.log(d3.event.layerX, d3.event.layerY;);
      });
...
```

**Comment by sungwoncho** [comment] 2016-08-31 01:56
I will try again soon and close if not a bug.

**Comment by Olical** [comment] 2016-09-08 11:35
Any thoughts on this? Reproducible as a test?

**Comment by sungwoncho** [comment] 2016-09-08 23:39
@Olical I am currently not working on a feature involving this bug and have some other priorities. But I will get back to this one.

**Comment by Olical** [comment] 2016-09-12 19:34
Since it doesn't seem to be a widespread issue (maybe a rare edge case?) I'll close this for now. Feel free to open it again if you hit it. A test that reproduces it would be brilliant, but no pressure.

Thanks for the initial report anyway! I'll keep this in mind.

**Closed by Olical** 2016-09-12 19:34 UTC

**Comment by Xalio08** [comment] 2017-06-01 11:15
I have a similar problem. It might be related to the fact that `this` is not a real d3 node.
`d3.mouse(this)` returns `[NaN,NaN]`, whereas `d3.mouse(d3.select('svg').select('g').node())` returns the correct value.
@BeshoyLouka workaround is good though.

**Comment by P1zz4br0etch3n** [comment] 2018-08-21 09:11
This also breaks zoom support because x and y in the transform object in d3 zoom event are also `NaN`.
